### ISSUE TITLE
systemctl error

### ISSUE THREAD

**Issue by mengzyou** [openSUSE/docker-containers#1]
When exectue the `systemctl` command on container, always got below error:

``` shell
09fd2fe788a7:/ # systemctl status mysql.service
Failed to get D-Bus connection: Unknown error -1
```

images vesion: `13.2`

``` shell
09fd2fe788a7:/ # cat /etc/os-release 
NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:13.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
```

**Comment by flavio** [comment]
That happens because right now systemd cannot run inside of Docker. That happens despite of the container OS/docker version being used.

You have to start mysql by hand, take a look at what is written inside of systemd's unit file for mysql.

Closing as invalid.

**Comment by mengzyou** [comment]
@flavio Got it, thank you very much!
