### ISSUE TITLE
Sass::SyntaxError: File to import not found or unreadable: font-awesome

### ISSUE THREAD

**Issue by wenchongyang** [openSUSE/docker-containers#103]
using the lasted image sha256:ce14800138d79204fb5d22493f4cb12a6520f22fd76967647b61cca38a30f922 when start up using http://172.31.0.237:3000 then the page show with error:
http://172.31.0.237:3000/500?fixes=true
 Sass::SyntaxError: File to import not found or unreadable: font-awesome
 Load paths:
 /srv/Portus/app/assets/images
 /srv/Portus/app/assets/javascripts
 /srv/Portus/app/assets/stylesheets
 /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/fonts
 /srv/Portus/vendor/bundle/ruby/2.5.0/gems/font-awesome-rails-4.7.0.3/app/assets/stylesheets

**Comment by mssola** [comment]
I think you are missing setting `RAILS_SERVE_STATIC_ASSETS` to `true`. See the [documentation](http://port.us.org/docs/assets.html) or the [examples](https://github.com/SUSE/Portus/tree/master/examples)

**Comment by wenchongyang** [comment]
yes setting the RAILS_SERVE_STATIC_FILES and RAILS_SERVE_STATIC_ASSETS   to true , then start success.

**Comment by mssola** [comment]
Great! Closing then :+1:
