### ISSUE TITLE
kmod package isn't installed

### ISSUE THREAD

**Issue by schidlo** [openSUSE/docker-containers#11]
I tried to run lsmod (which is part of kmod package) but it was missing in opensuse:13.2 image. This package was part of image before.

Is this change made by mistake or it is on purpose? Thank you for your answer.

**Comment by flavio** [comment]
We deliberately removed this package from the official images because 99% of the times there's no reason to allow a container to mess with the kernel of the host.

You can add the package back by installing it manually inside of your Dockerfile.
