### ISSUE TITLE
breaking changes without revision tagging

### ISSUE THREAD

**Issue by solvingj** [openSUSE/docker-containers#112]
The official OpenSUSE docker images are constantly being improved and that is a great thing.  However, organizations using these docker images often require reproducibility and predictability in the runtime behavior of containers. Thus, such organizations typically need to pin their CI builds and other automated processes to specific tag revision based on a point in time, rather than using the `latest` tag.  They can then deliberately move their pinned revision forward after testing new revisions at their own pace. This is a request to please begin leaving a trail of revision-marked or datestamped Docker tags for each released build on docker hub.   You can have a look at the `ubuntu` tag history for a reference of a model that addresses this situation and enables this workflow. 

https://hub.docker.com/_/ubuntu?tab=tags

Here I've opened a similar ticket and discussion for some `CentOS` images. 

https://github.com/sclorg/s2i-python-container/issues/301

The work of adding a tag is quite trivial, so I'm sure getting agreement internally in the team on whether or not to do this, and if so, what the tagging convention should be will take more time.

**Comment by Vogtinator** [comment]
For Leap 15.1 and Tumbleweed those tags exist, but only on `registry.opensuse.org`.

What the exact tag to refer to a specific image is can be seen in the `org.opensuse.reference` label:

```
> docker image inspect opensuse/leap:15.1 | grep reference
                "org.opensuse.base.reference": "registry.opensuse.org/opensuse/leap:15.1.3.11",
                "org.opensuse.reference": "registry.opensuse.org/opensuse/leap:15.1.3.11"
```

**Comment by solvingj** [comment]
Great, thank you.  I understand this minor version tagging won't be backported to older leap versions.
