### ISSUE TITLE
Any possibility we can get an ARM version of Tumbleweed or Leap

### ISSUE THREAD

**Issue by hurricanehrndz** [openSUSE/docker-containers#12]

**Comment by flavio** [comment]
We used to have one [here](https://build.opensuse.org/package/show/Virtualization:containers:images:openSUSE-42.1/openSUSE-42.1-docker-image). Right now it's not building, we can look into that in the next weeks.

However there's the problem about where we should push the image. The Docker Hub doesn't provide any distinction between x86 and ARM/Power/Z architectures.

A possible solutions could be:
- `docker pull opensuse/42.1:arm`
- `docker pull opensuse/arm:42.1`
- `docker pull opensuse/leap-arm:42.1`

Other ideas are welcome :)

**Comment by hurricanehrndz** [comment]
Awesome! I believe opensuse/arm:42.1 or opensuse/arm:tumbleweed works well.

**Comment by awafaa-zz** [comment]
My preference is to label the name spaces according to compiler triplet:
- <code> docker pull opensuse/aarch64:42.1 </code>
- <code> docker pull opensuse/armv7l:42.1 </code>
- <code> docker pull opensuse/armv6l:42.1 </code>
- <code> docker pull opensuse/ppc64:42.1 </code>
- <code> docker pull opensuse/s390x:42.1 </code>

This also enables growth for any additional architectures that get added

**Comment by awafaa-zz** [comment]
I'm waiting to hear back from ARM as to whether they agree on this proposal, as there are plans to have root name spaces within the docker hub too.

**Comment by afaerber** [comment]
@awafaa Any update on this? I've seen `aarch64/ubuntu` and `aarch64/debian` for instance. The former referenced in [96Boards CE Docker documentation](https://github.com/96boards/documentation/blob/master/ConsumerEdition/CE-Extras/DockerCE.md).

Otherwise agreed that `arm` is too generic; I wonder whether it should rather be `armv7hl` and `armv6hl`, as on [download.opensuse.org](http://download.opensuse.org/ports/)?

**Comment by tboerger** [comment]
We already got these repos prepared on jenkins, but we have not configured any worker except for `x86_64` so far:

* aarch64: `opensuse/aarch64:42.1`
* armv6l: `opensuse/armv6l:42.1`
* armv7l: `opensuse/armv7l:42.1`
* ppc64le: `opensuse/ppc64le:42.1`
* s390x: `opensuse/s390x:42.1`
* x86_64: `opensuse/amd64:42.1`

**Comment by hurricanehrndz** [comment]
I started making my own, so If you wish you can close this issue.

**Comment by flavio** [comment]
We are building the base images for aarch64, armv7l, ppc64le and even s390x on OBS:

 * [openSUSE Leap 42.2](http://download.opensuse.org/repositories/Virtualization:/containers:/images:/openSUSE-42.2/images/)
 * [openSUSE tumbleweed](http://download.opensuse.org/repositories/Virtualization:/containers:/images:/openSUSE-Tumbleweed/images/)

We have to automate their publishing to the docker hub. I'll create an internal ticket for that.
