### ISSUE TITLE
Don't install systemd by default

### ISSUE THREAD

**Issue by cyphar** [openSUSE/docker-containers#14]
Most users don't run `systemd` as their init system inside a container. So it's unnecessary to bloat the base images with all of `systemd`'s machinations (anybody can `zypper in ...` if they want).

**Comment by flavio** [comment]
Unfortunately we have to do that for openSUSE 13.2 and 42.1 because some systems tools (like `ps`) are dynamically linked against `libsystemd`, which is shipped inside of the `systemd` package. That is a major pita that has been solved by tumbleweed and SLE12 SP1 by splitting the `systemd` packages in two parts (one being `libsystemd`).

```
$ cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"
$ ldd `which ps`
    linux-vdso.so.1 (0x00007fffebdbc000)
    libprocps.so.3 => /usr/lib64/libprocps.so.3 (0x00007f8a72b95000)
    libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f8a7296b000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f8a72766000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f8a723be000)
    liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f8a72198000)
    libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f8a71eb1000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f8a71ca9000)
    libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f8a71a92000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8a71874000)
    /lib64/ld-linux-x86-64.so.2 (0x00005650d8c44000)
    libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f8a7166f000)
$ rpm -qf /usr/lib64/libsystemd.so.0
systemd-210-86.1.x86_64
```

**Comment by cyphar** [comment]
`<insert rant about libsystemd and why lib[your init system] is a bad idea for making libraries>`

But seriously, can we bring this up with the `systemd` maintainers? Seems like something that we should fix.

**Comment by flavio** [comment]
This has already been fixed inside of tumbleweed and sle12 sp2. We cannot do this change right now inside of 42.1, things are going to be better with the next release of leap
