### ISSUE TITLE
Running more than one service

### ISSUE THREAD

**Issue by zimmski** [openSUSE/docker-containers#2]
I want to use your openSUSE base images for some internal showcases. The problem is that I need to run more than one service inside the container e.g. PostgreSQL and some other applications.

What are you recommending for doing this? It would be ideal if I could use the usual systemctl/service commands to enable/start services.

(I know that it is best practice to use just one service per container but the images I need to create are special use-cases which run for a few days/weeks and are then just thrown away.)

**Comment by darix** [comment]
just run the normal init system

**Comment by zimmski** [comment]
You mean like this?

``` dockerfile
FROM opensuse:latest
MAINTAINER M Z

RUN zypper --non-interactive --gpg-auto-import-keys ref
RUN zypper --non-interactive install perl postgresql-server && systemctl enable postgresql.service

EXPOSE 5432

ENTRYPOINT ["/sbin/init"]
```

**Comment by flavio** [comment]
`/sbin/init` on recent versions of openSUSE is provided by systemd, which cannot run right now inside of Docker containers (despite of the host/guest combination).

You could rely on a simpler init system like runit or you could just use a script as entry point. Inside of the script you could start all the daemons you need. The only drawback of this approach is to take care of the cleanup of the running processes once the container is killed/stopped.

**Comment by tboerger** [comment]
There are various options for doing this like runit, monit or even something in the python world. I think there is no solution to rule them all :)

**Comment by darix** [comment]
or you could just one container per app and let them talk via network?;)

**Comment by tboerger** [comment]
> or you could just one container per app and let them talk via network?;)

That's the way how it should work :). But there are cases where i have done it different, like a rails application with a worker queue and a clockwork component, there i have added a Procfile (which gets processed by foreman) like it is available on Heroku.

**Comment by darix** [comment]
well while it is ugly to duplicate the rails code into multiple containers, it is not different from the ugliness of having to duplicate all the libs+data files for each service.

**Comment by zimmski** [comment]
I am trying to get as close to a normal VM as possible so it would be nice if systemctl/service would work. Usually i am using "supervisor" but that is not what I want to do with this project.

**Comment by tboerger** [comment]
But containers are not compareable with virtual machines

**Comment by darix** [comment]
so do one container per app and let them talk via network?

flavio just pointed me to:
- http://developerblog.redhat.com/2014/05/05/running-systemd-within-docker-container/
- https://github.com/docker/docker/issues/3629

hth.

p.s.: before i moved to systemd's restart feature i had been using runit for this.

**Comment by zimmski** [comment]
I am aware of the container vs VM discussions, docker best practices, and so on. I do not want to discuss this here.

I want to discuss how more than one service could be started with their init/systemd files, run by a processmanager/init system using the openSUSE image as its base in the easiest way possible. Since using systemd does not seem to work, yet (@darix: I read the same articles, privileged containers are a no-go) I will try to use a simple bash script to start the services thanks @flavio I hope this works for us.

**Comment by flavio** [comment]
Closing, not pertinent with this project
