### ISSUE TITLE
Include GPG keys for standard repositories

### ISSUE THREAD

**Issue by garretraziel** [openSUSE/docker-containers#3]
In current `opensuse:13.2` image there are no GPG keys for these repos: `repo-non-oss`, `repo-oss`, `repo-oss`, `repo-update` and `repo-update-non-oss` so when creating image based on `opensuse:13.2`, user has to install packages with `--gpg-auto-import-keys` or import keys by hand. But another problem is that `opensuse:13.2` doesn't include any certificates, so:
1. user is unable to install `ca-certificates` because GPG keys for repos are not imported
2. user is unable to download these GPG keys from anywhere, because he has no certificates to check whether he is downloading from trusted url.

I think that this forces user to build insecure images, see https://github.com/os-autoinst/openQA/pull/340#discussion_r28589978

**Comment by flavio** [comment]
The fixed images are going to show up as soon as [this PR](https://github.com/docker-library/official-images/pull/680) is closed.

**Comment by flavio** [comment]
The updated images are currently building. They are going to be available on the Docker Hub within the next hours.
