### ISSUE TITLE
Update Portus to 2.1

### ISSUE THREAD

**Issue by zifik** [openSUSE/docker-containers#30]
Please create a branch or tag for Portus 2.1.

Would also be nice if it is subsequently available via hub.docker.com as well.

**Comment by lauriholmas** [comment]
Also a branch for Portus 2.2 would be nice to have!

**Comment by yongzhang** [comment]
any schedule for Portus 2.2?

**Comment by mssola** [comment]
Done. Sorry for all the troubles. It took a bit because we also re-did how we handle the docker image from now on.
