### ISSUE TITLE
Wrong packages and paths

### ISSUE THREAD

**Issue by m407** [openSUSE/docker-containers#33]
1. In openSUSE-42.2 config.kiwi contains non existing for 42.2 project openSUSE-release-mini
2. In derived_images/systemd/Dockerfile paths for init is wrong. In openSUSE init located in /sbin/init and anyway it's  useless. CMD directive should by like this
CMD ["/usr/lib/systemd/systemd"]

**Comment by tboerger** [comment]
> In openSUSE-42.2 config.kiwi contains non existing for 42.2 project openSUSE-release-mini

```
bash-4.3# cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.2"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.2"
PRETTY_NAME="openSUSE Leap 42.2"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.2"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

bash-4.3# zypper search release-mini
Loading repository data...
Reading installed packages...

S | Name                  | Summary  | Type
--+-----------------------+----------+--------
i | openSUSE-release-mini | openSUSE | package
```

> In derived_images/systemd/Dockerfile paths for init is wrong. In openSUSE init located in /sbin/init and anyway it's useless. CMD directive should by like this
> CMD ["/usr/lib/systemd/systemd"]

I don't know why somebody wants to use that container anyway, but this can be solved quite easy.

**Comment by m407** [comment]
zypper lr -u
 | Alias               | Name                              | Enabled | GPG Check | Refresh | URI                                                                   
--+---------------------+-----------------------------------+---------+-----------+---------+-----------------------------------------------------------------------
1 | repo-non-oss        | openSUSE-Leap-42.2-Non-Oss        | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.2/repo/non-oss/suse/
2 | repo-oss            | openSUSE-Leap-42.2-Oss            | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/distribution/leap/42.2/repo/oss/suse/    
3 | repo-update         | openSUSE-Leap-42.2-Update         | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.2/oss/                    
4 | repo-update-non-oss | openSUSE-Leap-42.2-Update-Non-Oss | Yes     | (r ) Yes  | Yes     | http://download.opensuse.org/update/leap/42.2/non-oss/                

zypper search release-mini

Loading repository data...
Reading installed packages...
No matching items found.

http://software.opensuse.org/package/openSUSE-release-mini?search_term=release-mini - gives the same result

**Comment by tboerger** [comment]
The systemd example have been fixed now.

**Comment by tboerger** [comment]
It's indeed a system package, than I'm asking where it comes from...

```
S | Name                  | Type    | Version    | Arch   | Repository
--+-----------------------+---------+------------+--------+------------------
i | openSUSE-release-mini | package | 42.2-1.150 | x86_64 | (System Packages)
```

@davidcassany maybe you want to fix/resolve that? Looks like openSUSE-release-mini doesn't exist anymore within 42.2 but it's still part of the kiwi definition.

**Comment by m407** [comment]
You are right. I built it locally so I got an error. But when it is built in OBS instance everything Ok.
