### ISSUE TITLE
portus version in this container is dev, would be nice to have versions by releases

### ISSUE THREAD

**Issue by lauriholmas** [openSUSE/docker-containers#42]
The portus version in the portus container is currently 2.3-dev. Would be nice to have branched/tagged builds which refer the portus release versions. There is tag for 2.0, but since that 2.1 and 2.2 have come out. ( I think it was 2.2 that required database migrations, which was a bit of an unpleasant surprise).  I guess having versioned builds would require versioned releases of portus into the repo that zypper pulls them from.

**Comment by mssola** [comment]
We are planning to fix that. Sorry for the troubles.

**Comment by mssola** [comment]
This has already been done. We now provide a tag for 2.1 and 2.2. Furthermore, note that for 2.3-dev and master we are now using Puma. I've added some examples on how to deploy this new image in the PR SUSE/Portus#1254.

Thanks for the patience 😅
