### ISSUE TITLE
Leap 42.3 images

### ISSUE THREAD

**Issue by afaerber** [openSUSE/docker-containers#55]
There is no openSUSE-42.3 directory yet, and it's undocumented how openSUSE-42.2/root.tar.bz2 or its predecessors were actually generated.

**Comment by jordimassaguerpla** [comment]
This was fixed on May 21st https://github.com/openSUSE/docker-containers/commit/615aeef8f7bca39d1b4a4fa8a00f1824ac8d277c. We just forgot to close this issue.

**Comment by jayvdb** [comment]
There isnt a 42.3 tag in https://hub.docker.com/r/library/opensuse/tags/ yet.

**Comment by afaerber** [comment]
And not in https://hub.docker.com/r/opensuse/amd64/tags/ either.

**Comment by jayvdb** [comment]
@flavio, can we expect 42.3 docker images any time soon?

**Comment by flavio** [comment]
Sure, we are going to publish them at the same time the official openSUSE Leap 42.3 is released.

**Comment by jayvdb** [comment]
They are available now.
