### ISSUE TITLE
docker pull opensuse/portus - Error response from daemon: manifest for opensuse/portus:latest not found

### ISSUE THREAD

**Issue by rhrpr** [openSUSE/docker-containers#56]
Has there been an error in the latest commit?

**Comment by mssola** [comment]
Check the image on the [Docker hub](https://hub.docker.com/r/opensuse/portus/) and in the [documentation](https://github.com/openSUSE/docker-containers/tree/master/derived_images/portus#portus-official-docker-image), there's no `latest` tag. You should use `head` or one tagged version (e.g. `v2.2`).
