### ISSUE TITLE
Update libusb-1_0-0

### ISSUE THREAD

**Issue by garretraziel** [openSUSE/docker-containers#6]
We are using Qemu inside openSUSE container. Newest version of openSUSE image (version 13.2) contains really old version of libusb-1_0-0 for some reason and running Qemu fails with:

```
QEMU: /usr/bin/qemu-system-x86_64: symbol lookup error: /usr/bin/qemu-system-x86_64: undefined symbol: libusb_free_ss_endpoint_companion_descriptor
```

Updating libusb during image building (with `RUN zypper --non-interactive in libusb-1_0-0`) installs newest version of libusb that works with Qemu.

Is there any reason why older version is included?

**Comment by adrianschroeter** [comment]
it looks like the repository order inside of the kiwi file is wrong, so the oldest (GA) package gets prefered actually.

**Comment by flavio** [comment]
I'll submit the new image to the Docker Hub once it's done. Thanks @adrianschroeter for the tip.

**Comment by flavio** [comment]
Fixed
