### ISSUE TITLE
File repo reference in opensuse:latest tag 

### ISSUE THREAD

**Issue by kcgen** [openSUSE/docker-containers#7]
repo-oss in the the latest opensuse tag is using a file:/ reference instead of the web source: http://download.opensuse.org/distribution/13.2/repo/oss 

For those who need a work around in docker, use the following prior to installing packages:

zypper rr repo-oss && zypper addrepo http://download.opensuse.org/distribution/13.2/repo/oss repo-oss && zypper ref

---

 [kcroft@hoya ~] docker run -i -t opensuse:latest /bin/bash

 c87870fcfaf6:/ # zypper repos -d  
 | Alias               | Name                | Enabled | Refresh | Priority | Type   | URI                                                                                | Service
 --+---------------------+---------------------+---------+---------+----------+--------+----------------+--------
 1 | repo-non-oss        | repo-non-oss        | Yes     | Yes     |   99     | rpm-md | http://download.opensuse.org/repositories/openSUSE:/13.2:/NonFree/standard         |        

 2 | repo-non-oss-update | repo-non-oss-update | Yes     | Yes     |   99     | rpm-md | http://download.opensuse.org/repositories/openSUSE:/13.2:/NonFree:/Update/standard |        

 3 | repo-oss            | repo-oss            | Yes     | Yes     |   99     | rpm-md | file:/base-system/usr/src/packages/SOURCES/repos/openSUSE:13.2/standard **<-- this is the problem**

 4 | repo-oss-updates    | repo-oss-updates    | Yes     | Yes     |   99     | rpm-md | http://download.opensuse.org/repositories/openSUSE:/13.2:/Update/standard          |

**Comment by flavio** [comment]
Fixed.
