### ISSUE TITLE
Missing repository for openSUSE-release-mini package

### ISSUE THREAD

**Issue by ghost** [openSUSE/docker-containers#8]
Hi,

I'm trying to reproduce the docker image build. I installed _openSUSE 13.2_ in a virtual machine, added the `kiwi` repository and tried to build a rootfs with the `config.kiwi` template.

One package, which is going to be installed is `openSUSE-release-mini`. With the current configuration the build process fails on my machine, because it can't find the package. The `openSUSE-release-mini` can be found [here](http://download.opensuse.org/repositories/openSUSE:/13.2:/Live/standard/x86_64/) - so the _13.2:/Live/standard_ repository is used. After adding:

``` bash
<repository type="rpm-md">
  <source path="obs://openSUSE:13.2:Live/standard"/>
</repository>
```

it works perfectly and the rootfs is build with:

``` bash
kiwi --prepare . --root /root/kiwi/docker/openSUSE-13.2_rootfs
```

I guess the repository should be added to the `config.kiwi` file - or did I miss to install something on my host system?

/cc @flavio

**Comment by flavio** [comment]
I have good news for you, we just reduced the image size to ~80M.

We worked together with the kiwi author, we cannot shrink the image size even further without breaking the system.

Can I close this issue?

**Comment by flavio** [comment]
The smaller images are going to be on the Docker Hub as soon as https://github.com/docker-library/official-images/pull/894 is merged.

**Comment by ghost** [comment]
@flavio Thanks for that update! Another question: Is the current `config.kiwi` then up to date? Because I got errors related to the `openSUSE-release-mini` package :(

**Comment by flavio** [comment]
Sorry for the late response. The contents of this repository are used to build the images on the open build service (there's a link inside of the README). So yes, everything should work out of the box with kiwi
