### ISSUE TITLE
not able to bind to a differnt port

### ISSUE THREAD

**Issue by adnoh** [openSUSE/docker-containers#98]
the line `export PORTUS_PUMA_HOST="0.0.0.0:3000"` in /init leads to not being able to set the binding via docker/kubernetes which should be possible by exposing the mentioned environment variable.
It is unnecessary, because of Port 3000 is the default in puma and the puma.rb from portus.
Btw, I think all of this exports in /init are a problem to limit configuration of the container via env variables

**Comment by mssola** [comment]
@adnoh Portus binds to 3000, but in the container world you can do port mapping. See my explanation [here](https://github.com/openSUSE/docker-containers/pull/101#issuecomment-374994885).
